FROM ubuntu:latest AS base

# Install dependencies gcc
RUN apt-get update && apt-get install -y \
    gcc g++\
    && rm -rf /var/lib/apt/lists/*

# add in the files
COPY ./calculate_pi.cpp /build/calculate_pi.cpp

# compile the code
RUN g++ /build/calculate_pi.cpp -o /build/calculate_pi -fopenmp


FROM ubuntu:latest AS final
COPY --from=base /build/calculate_pi /app/calculate_pi
COPY --from=base /lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/

CMD ["/app/calculate_pi", "1000000"]
# ENTRYPOINT [ "/app/calculate_pi" ]
