services:

  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_PORT=5000
    networks:
      - app_net
    volumes:
      - app_data:/app/data
      

  listener:
    image: listener
    build:
      context: ./listener
      dockerfile: Dockerfile
    environment:
      - TARGET_URL=http://server:5000
    networks:
      - app_net
  

networks:
  app_net:
    # Specify driver options
    driver: bridge


volumes:
  app_data:
    driver: local